name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Get the version
        id: get_version
        run: | 
            echo "APPSETTINGS_VERSION=$(git describe --tags --always --abbrev=7)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
            GOOS=windows GOARCH=amd64 go build -o telegram_notify_action_${{ steps.get_version.outputs.APPSETTINGS_VERSION }}.exe
            GOOS=linux GOARCH=amd64 go build -o telegram_notify_action_${{ steps.get_version.outputs.APPSETTINGS_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            telegram_notify_action_${{ steps.get_version.outputs.APPSETTINGS_VERSION }}.exe
            telegram_notify_action_${{ steps.get_version.outputs.APPSETTINGS_VERSION }}
  
